# Generated by Django 5.1 on 2024-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnb_app", "0008_review"),
        ("users", "0002_alter_profile_profile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bookings_made",
            field=models.ManyToManyField(blank=True, to="bnb_app.listing"),
        ),
    ]
