# Generated by Django 5.1 on 2024-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_bookings_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="book_count",
            field=models.IntegerField(default=0),
        ),
    ]
