# Generated by Django 5.1 on 2024-10-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnb_app", "0008_review"),
        ("users", "0004_profile_book_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="book_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bookings_made",
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_count", models.IntegerField(default=0)),
                (
                    "bookings_made",
                    models.ManyToManyField(blank=True, to="bnb_app.listing"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
