# Generated by Django 5.1 on 2024-10-01 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_profile_book_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookings",
            options={"verbose_name_plural": "Bookings"},
        ),
    ]
