# Generated by Django 5.1 on 2024-09-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bnb_app", "0005_alter_listing_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bnb_app.rating"
            ),
        ),
    ]
