# Generated by Django 5.1 on 2024-09-26 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bnb_app", "0006_rating_alter_review_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
